name: Deploy via Cloudflare Tunnel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install cloudflared
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Setup SSH over Cloudflare
        env:
          CF_SERVICE_TOKEN: ${{ secrets.CF_SERVICE_TOKEN }}
        run: |
          mkdir -p ~/.ssh
          cloudflared access ssh-config --hostname ssh.manuel.best --destination ~/.ssh/config --token "${CF_SERVICE_TOKEN}"

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem manuel@ssh.manuel.best "cd /home/manuel/Manuel.Best/manuel-best-vue && ./deploy.sh"
